services:
  db:
    image: postgres:17
    container_name: TO-DO
    environment:
      POSTGRES_PASSWORD: TO_DO
      POSTGRES_USER: myuser
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d mydatabase" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
